"""
Maitain constant variable will be used in this program
"""
import numpy as np


LOAD = [1, 0, 0, 0, 0 ,0]

GLASS_EPOXY= 'glass_epoxy'
GRAPHITE_EPOXY = "graphite_epoxy"
CARBON_EPOXY = "carbon_epoxy"
T300_5308 = "T300_5308"

SAFETY_FACTOR = 2 

# genetic algorithm parameter

POPULATION_NUMBER = 40 
MUTATION_PROBABILITY=0.8
CROSSOVER_PROBABLITY=0.8
ELITIST_PERCENT=0.5

# parents selection
ACTIVE_GROUP = 0.2
PROPER_GROUP = 0.5
POTENTIAL_GROUP = 0.3
PROPER_PARENTS_PERCENT = 0.4
PARENTS_BY_FITNESS_PERCENT = 0.4
PARENTS_BY_FITNESS_PERCENT = 0.0

CHROMOSOME_LENGTH_LOWER_BOUND = 8 
CHROMOSOME_LENGTH_UPPER_BOUND = 15 
GA_RUNTIMES = 50
# Material
LAYER_HEIGHT = 0.000165

MATERIAL = [GRAPHITE_EPOXY]
#MATERIAL = [GRAPHITE_EPOXY,GLASS_EPOXY, CARBON_EPOXY] #GLASS_EPOXY
ANGLE_TYPE = 2 

