BATCH: 35000
TOTAL_DATA_NUMBER: 142836
TRAINING_PERCENT: 0.8
FILE_PATH: "./train_data/"
FILE_NAME: "clt_data.csv"

NUMBER_OF_INPUTS: 16
NUMBER_OF_OUTPUTS: 2 
LEARNING_RATE: 0.00020
NUMBER_OF_TRAINING_SAVE_STATE: 5000
SAVING_PLACE_OF_TRAINING_MODEL: "./log"
SAVING_PLACE_OF_TRAINING_PROCESS: "./trained_model/chrosome/model"
