BATCH: 50000
TOTAL_DATA_NUMBER: 141740
TRAINING_PERCENT: 0.8
FILE_PATH: "./train_data/"
FILE_NAME: "m1_normalization_reindex.csv"

TRAINING_RUNTIMES: 50
NUMBER_OF_INPUTS: 16
NUMBER_OF_OUTPUTS: 2 
LEARNING_RATE: 0.01
NUMBER_OF_TRAINING_SAVE_STATE: 10 
SAVING_PLACE_OF_TRAINING_MODEL: "./train_model"
SAVING_PLACE_OF_TRAINING_PROCESS: "./log"
