BATCH: 70
TOTAL_DATA_NUMBER: 1324
TRAINING_PERCENT: 0.8
FILE_PATH: "./train_data/"
FILE_NAME: "train_data.csv"

NUMBER_OF_INPUTS: 16
NUMBER_OF_OUTPUTS: 2 
LEARNING_RATE: 0.001
NUMBER_OF_TRAINING_SAVE_STATE: 5000
SAVING_PLACE_OF_TRAINING_MODEL: "./log"
SAVING_PLACE_OF_TRAINING_PROCESS: "./trained_model/chrosome/model"
